# Generated by Django 4.0.3 on 2022-03-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.ImageField(default=None, upload_to='./avatar', verbose_name='Ảnh đại diện'),
        ),
    ]
