# Generated by Django 4.0.2 on 2022-03-03 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Khoa',
            fields=[
                ('MaKhoa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenKhoa', models.CharField(max_length=50)),
                ('GhiChu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lop',
            fields=[
                ('MaLop', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenLop', models.CharField(max_length=50)),
                ('GhiChu', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NienKhoa',
            fields=[
                ('MaNienKhoa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenNienKhoa', models.CharField(max_length=50)),
                ('GhiChu', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Truong',
            fields=[
                ('MaTruong', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenTruong', models.CharField(max_length=50)),
                ('DiaChi', models.CharField(default='', max_length=100)),
                ('GioiThieu', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TrangThai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrangThai', models.BooleanField(default=False)),
                ('MaNienKhoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infor.nienkhoa')),
            ],
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('MaSV', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('HoTen', models.CharField(max_length=50)),
                ('NgaySinh', models.DateTimeField()),
                ('GioiTinh', models.BooleanField(default=True)),
                ('DanToc', models.CharField(max_length=50)),
                ('DaiChi', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('NoiO', models.CharField(max_length=100)),
                ('GhiChu', models.CharField(default='', max_length=200)),
                ('Malop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infor.lop')),
            ],
        ),
        migrations.CreateModel(
            name='Nganh',
            fields=[
                ('MaNganh', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenNganh', models.CharField(max_length=50)),
                ('GhiChu', models.CharField(default='', max_length=100)),
                ('MaKhoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infor.khoa')),
            ],
        ),
        migrations.AddField(
            model_name='lop',
            name='MaNganh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infor.nganh'),
        ),
        migrations.AddField(
            model_name='lop',
            name='MaNienKhoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infor.nienkhoa'),
        ),
        migrations.AddField(
            model_name='khoa',
            name='MaTruong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infor.truong'),
        ),
    ]
