# Generated by Django 4.0.2 on 2022-03-03 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truong',
            old_name='GioiThieu',
            new_name='Gioithieu',
        ),
        migrations.RemoveField(
            model_name='trangthai',
            name='id',
        ),
        migrations.AddField(
            model_name='trangthai',
            name='MaSV',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='infor.sinhvien', unique=True),
        ),
        migrations.AlterField(
            model_name='khoa',
            name='GhiChu',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='GioiTinh',
            field=models.CharField(default='Nam', max_length=10),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='NgaySinh',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trangthai',
            name='TrangThai',
            field=models.CharField(default='Chưa ra trương', max_length=100),
        ),
        migrations.CreateModel(
            name='avata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imge', models.ImageField(upload_to='images/')),
                ('MaSV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infor.sinhvien')),
            ],
        ),
    ]
